// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/ai-assistants.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$3 from "./apps/decohub.ts";
import * as $$$$$$$$$$$4 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Achievements.tsx";
import * as $$$$$$1 from "./sections/BlogPost.tsx";
import * as $$$$$$2 from "./sections/BlogPosts.tsx";
import * as $$$$$$3 from "./sections/Cases.tsx";
import * as $$$$$$4 from "./sections/Chart.tsx";
import * as $$$$$$5 from "./sections/Contact.tsx";
import * as $$$$$$6 from "./sections/Faq.tsx";
import * as $$$$$$7 from "./sections/FaqImage.tsx";
import * as $$$$$$8 from "./sections/Footer.tsx";
import * as $$$$$$9 from "./sections/GridContent.tsx";
import * as $$$$$$10 from "./sections/Header.tsx";
import * as $$$$$$22 from "./sections/hero-1.tsx";
import * as $$$$$$23 from "./sections/hero-2.tsx";
import * as $$$$$$11 from "./sections/Hero.tsx";
import * as $$$$$$24 from "./sections/hero2.tsx";
import * as $$$$$$12 from "./sections/ImageText.tsx";
import * as $$$$$$13 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$14 from "./sections/Logos.tsx";
import * as $$$$$$15 from "./sections/Partnerships.tsx";
import * as $$$$$$16 from "./sections/RichText.tsx";
import * as $$$$$$17 from "./sections/SimpleHeader.tsx";
import * as $$$$$$18 from "./sections/Statistics.tsx";
import * as $$$$$$19 from "./sections/Testimonials.tsx";
import * as $$$$$$20 from "./sections/TextWithCards.tsx";
import * as $$$$$$21 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Achievements.tsx": $$$$$$0,
    "site/sections/BlogPost.tsx": $$$$$$1,
    "site/sections/BlogPosts.tsx": $$$$$$2,
    "site/sections/Cases.tsx": $$$$$$3,
    "site/sections/Chart.tsx": $$$$$$4,
    "site/sections/Contact.tsx": $$$$$$5,
    "site/sections/Faq.tsx": $$$$$$6,
    "site/sections/FaqImage.tsx": $$$$$$7,
    "site/sections/Footer.tsx": $$$$$$8,
    "site/sections/GridContent.tsx": $$$$$$9,
    "site/sections/Header.tsx": $$$$$$10,
    "site/sections/hero-1.tsx": $$$$$$22,
    "site/sections/hero-2.tsx": $$$$$$23,
    "site/sections/Hero.tsx": $$$$$$11,
    "site/sections/hero2.tsx": $$$$$$24,
    "site/sections/ImageText.tsx": $$$$$$12,
    "site/sections/ImageWithParagraph.tsx": $$$$$$13,
    "site/sections/Logos.tsx": $$$$$$14,
    "site/sections/Partnerships.tsx": $$$$$$15,
    "site/sections/RichText.tsx": $$$$$$16,
    "site/sections/SimpleHeader.tsx": $$$$$$17,
    "site/sections/Statistics.tsx": $$$$$$18,
    "site/sections/Testimonials.tsx": $$$$$$19,
    "site/sections/TextWithCards.tsx": $$$$$$20,
    "site/sections/Theme/Theme.tsx": $$$$$$21,
  },
  "apps": {
    "site/apps/deco/ai-assistants.ts": $$$$$$$$$$$0,
    "site/apps/deco/blog.ts": $$$$$$$$$$$1,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$2,
    "site/apps/decohub.ts": $$$$$$$$$$$3,
    "site/apps/site.ts": $$$$$$$$$$$4,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
